# Test

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Nodejs
      run: |
        sudo apt install nodejs

    - name: Run
      run: |
        nodejs basics.js
        nodejs test.js

    - name: Run from sub folder
      run: |
        cd ; nodejs test.js
